//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRW1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SR-7BM3QM1\\SQLEXPRESS;Initial Catalog=TRW12;Integrated Security=True;" +
            "Pooling=False")]
        public string TRWConnectionString {
            get {
                return ((string)(this["TRWConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Gilberto\\SQLEXPRESS;AttachDbFilename=\"C:\\Program Files\\Microsoft SQL " +
            "Server\\MSSQL10.SQLEXPRESS\\MSSQL\\DATA\\TRW23.mdf\";Integrated Security=True")]
        public string TRW23ConnectionString {
            get {
                return ((string)(this["TRW23ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SR-7BM3QM1\\SQLEXPRESS;Initial Catalog=TRW12;Integrated Security=True;" +
            "Pooling=False")]
        public string TRW12ConnectionString {
            get {
                return ((string)(this["TRW12ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SR-7BM3QM1\\SQLEXPRESS;Initial Catalog=TRW11;Integrated Security=True;" +
            "Pooling=False")]
        public string TRW11ConnectionString {
            get {
                return ((string)(this["TRW11ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SR-7BM3QM1\\SQLEXPRESS;Initial Catalog=TRW1;Integrated Security=True;P" +
            "ooling=False")]
        public string TRW1ConnectionString {
            get {
                return ((string)(this["TRW1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SR-7BM3QM1\\SQLEXPRESS;Initial Catalog=TRW333;Integrated Security=True" +
            ";Pooling=False")]
        public string TRW33ConnectionString {
            get {
                return ((string)(this["TRW33ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Daniel-PC\\SQLEXPRESS;Initial Catalog=TRW333;Integrated Security=True;" +
            "Pooling=False")]
        public string TRW333ConnectionString {
            get {
                return ((string)(this["TRW333ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\DBprueba.mdf;Integrated" +
            " Security=True;User Instance=True")]
        public string DBpruebaConnectionString {
            get {
                return ((string)(this["DBpruebaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Gilberto\\SQLEXPRESS;Initial Catalog=TRW444;Integrated Security=True;P" +
            "ooling=False")]
        public string TRW444ConnectionString {
            get {
                return ((string)(this["TRW444ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Gilberto\\SQLEXPRESS;Initial Catalog=LogActividades;Integrated Securit" +
            "y=True;Pooling=False")]
        public string LogActividadesConnectionString {
            get {
                return ((string)(this["LogActividadesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=gilberto\\sqlexpress;Initial Catalog=DimCustomer;Integrated Security=T" +
            "rue;Pooling=False")]
        public string DimCustomerConnectionString {
            get {
                return ((string)(this["DimCustomerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GILBERTO\\SQLEXPRESS;Initial Catalog=PASVA444;Integrated Security=True" +
            ";Pooling=False")]
        public string PASVA444ConnectionString {
            get {
                return ((string)(this["PASVA444ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=TRW11;Integrated Security=True;Pooling=F" +
            "alse")]
        public string TRW11ConnectionString1 {
            get {
                return ((string)(this["TRW11ConnectionString1"]));
            }
        }
    }
}
